### ISSUE TITLE
Please include additional information

### ISSUE THREAD

**Issue by CTroessaert** [MicrosoftDocs/IntuneDocs.fr-fr#27]
Dear, as MSFT Employee, I'd like to add information related to EnterpriseEnrollment-s and EnterpriseEnrollment talked in this article: https://blogs.technet.microsoft.com/intunesupport/2017/03/04/which-cnames-to-use-for-auto-discovery-during-mdm-enrollment/

customer are sometime using old endpoint and it's nice to get further information.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ liaison des problèmes GitHub.*

* ID: bcaacea8-3551-042a-5a13-555ea5358562
* Version Independent ID: c4b98801-3462-60ab-640c-430713707540
* Content: [Configurer l’inscription d’appareils Windows à l’aide de Microsoft Intune](https://docs.microsoft.com/fr-be/intune/windows-enroll#enable-windows-enrollment-without-azure-ad-premium)
* Content Source: [intune/windows-enroll.md](https://github.com/MicrosoftDocs/IntuneDocs.fr-fr/blob/live/intune/windows-enroll.md)
* Service: **microsoft-intune**
* Product: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/IntuneDocs #1754](https://github.com/MicrosoftDocs/IntuneDocs/issues/1754) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @CTroessaert 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/1754.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
